name: Deploy pages
on:
  push:
    branches:
      - master
jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.16.0
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: 'pnpm'
      - name: Build package
        run: pnpm install && pnpm run build
      - name: Build pages
        run: cd pages && pnpm install && pnpm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: pages/dist
          CLEAN: true
          SINGLE_COMMIT: true